export const 
  GET_PARKING_LOTS_REQUEST = "PARKING_LOT:GET_PARKING_LOTS_REQUEST",
  GET_PARKING_LOTS_SUCCESS = "PARKING_LOT:GET_PARKING_LOTS_SUCCESS",
  GET_PARKING_LOTS_FAILURE = "PARKING_LOT:GET_PARKING_LOTS_FAILURE",
  SEARCH_PARKING_LOTS_REQUEST = "PARKING_LOT:SEARCH_REQUEST",
  SEARCH_PARKING_LOTS_SUCCESS = "PARKING_LOTS:SEARCH_SUCCESS",
  SEARCH_PARKING_LOTS_FAILURE = "PARKING_LOTS:SEARCH_FAILURE"; 