export const FETCH_PARKING_LOTS_REQUEST = 'PARKING_LOT:FETCH_REQUEST';
export const FETCH_PARKING_LOTS_SUCCESS = 'PARKING_LOT:FETCH_SUCCESS';
export const FETCH_PARKING_LOTS_FAILURE = 'PARKING_LOT:FETCH_FAILURE';
